name: Terraform Drift Detection

on:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  check-drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: environments/test

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode
        working-directory: environments/test

      - name: Check for Drift
        if: steps.plan.outputs.exitcode == 2
        run: |
          echo "Infrastructure drift detected. Please review."
          exit 1
      - name: Create Jira Ticket if Drift Found
        run: |
          if grep -q "DRIFT_DETECTED" drift.log; then
            curl -X POST -H "Authorization: Bearer ${{ secrets.JIRA_API_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{ "fields": { "project": { "key": "${{ secrets.JIRA_PROJECT_KEY }}" }, "summary": "Terraform Drift Detected", "description": "Infrastructure drift detected in environment", "issuetype": { "name": "Task" } } }' \
              "${{ secrets.JIRA_URL }}/rest/api/2/issue/"
          fi          
